ALTER TABLE users ADD COLUMN IF NOT EXISTS partner_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS partner_sexual_orientation TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS partner_ethnicity TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS partner_hair TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS partner_eyes TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS partner_height TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS partner_body_type TEXT;
